# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#
# global site settings
#
title: testdeck 
email: testdeck2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Testdeck - Your one stop solution for object oriented testing with Mocha, Jasmine or Jest
baseurl: ""
url: "https://testdeck.org"

#
# build settings
#
markdown: kramdown
remote_theme: testdeck/testdeck-jekyll-theme@gh-1
plugins:
  - jekyll-feed
  - jekyll-remote-theme

#
# excludes
#
exclude:
  - README.md
  - attic

#
# google custom search engine
#
gcse:
  id: 010650276315653629951:v3s_qe8occu 
  host: www.testdeck.org

